export const STRINGS = {
    appName: 'Plié',
    splash: {
        title: 'Plié',
        subtitle: 'ELEVATE THE MOVEMENT',
        footer1: 'Your Dance - Your Stage',
        footer2: 'Anyplace...',
    },
    login: {
        title: 'Plié',
        subtitle: 'ELEVATE THE MOVEMENT',
        emailLabel: 'Email',
        passwordLabel: 'Password',
        emailPlaceholder: 'email@gmail.com',
        passwordPlaceholder: 'Password',
        signIn: 'Sign In',
        forgotPassword: 'Forgot Password?',
        guest: 'Enter as Guest',
        notAMember: 'Not a member?',
        signUpHere: 'Sign Up Here',
        orSignInWith: 'Or Sign In With',
        validEmailError: 'Please enter a valid email address',
        validPasswordError: 'Password must be at least 6 characters',
        loginSuccess: 'Logged in successfully!',
        loginError: 'Login failed. Please check your credentials.',
        unexpectedError: 'An unexpected error occurred.',
    },
    search: {
        greetingTitle: 'Hello',
        greetingGuest: 'Hello Guest!',
        greetingSub: "Are you ready to dance? Explore today's\nmovements.",
        searchPlaceholder: 'Search events...',
        loadingEvents: 'Loading events...',
        noEventsFound: "We couldn't find any events matching your search criteria.",
    },
    favorites: {
        title: 'Your Favorite Events!',
        subtitle: 'Find your favorite events here....',
        emptyState: 'You haven\'t added any favorite events yet!',
    },
    eventDetails: {
        title: 'Event Details',
        aboutEvent: 'About Event',
        bookNow: 'Book Now',
        eventNotFound: 'Event not found.',
        free: 'Free',
    },
    profile: {
        myTickets: 'My Tickets',
        paymentMethods: 'Payment Methods',
        notificationSettings: 'Notification Settings',
        helpSupport: 'Help & Support',
        logout: 'Logout',
        logoutTitle: 'Logout',
        logoutConfirm: 'Are you sure you want to log out?',
        cancel: 'Cancel',
        logoutSuccess: 'Logged out successfully',
    },
};
